version: '3.3'
services:
  post_db:
    env_file:
      - .env              
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db  
  ui:
    env_file:
      - .env      
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
  post:
    env_file:
      - .env
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - front_net      
      - back_net
  comment:
    env_file:
      - .env     
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - front_net      
      - back_net

volumes:
  post_db:

networks:
  back_net:
  front_net:        

